### ISSUE TITLE
Decimal fields halting the progress

### ISSUE THREAD

**Issue by osama3101995** [madingess/EasyApplyBot#24]
Linkedin introduced decimal fields and the bot doesnt understand what to enter in it which leads to error asking to enter value similar to 0.0 resulting in lock that I have to close everytime.

**Comment by voidbydefault** [comment]
That issue has been fixed in my repo. Use the code from here: 
https://github.com/voidbydefault/EasyApplyBot/

I am also testing the fix for new question about 'how many weeks' notice'. It will be done in a day or two.

**Comment by osama3101995** [comment]
Hey @voidbydefault, Thanks for the updates! I think its still isnt working for some jobs. such as this:

https://www.linkedin.com/jobs/search/?currentJobId=3625685338

is it because it is in another language?

**Comment by voidbydefault** [comment]
Decimal and "notice in weeks" have been fixed, tested and confirmed. Did you use the script from my repo?

Also, the job you shared is in German language so probably that's the cause. It uses English to detect keywords to provide responses and in cases where it fails to find the keyword, it either provides a default response or the last option in the list.

**Comment by madingess** [comment]
Dear @osama3101995 ,

This should be fixed now with contributions from @voidbydefault . 

Also, please note, as stated by @voidbydefault , the bot uses English keywords and may not work as expected with other languages.
